import { BASE_STATS, DEFAULT_APPEARANCE_ID, DEFAULT_HUMAN_HERITAGE_ID, RACES, normalizeHumanHeritageId } from "../data/character";
import { addBonuses } from "./stats";
import { buildDefaultVisited } from "./map";
import { getDefaultBattlePouch } from "./inventory";
import type { Companion, GameFlags, Inventory, Player } from "./types";

export { buildDefaultVisited };

export function getInitialInventory(): Inventory {
  return { moonmint: 1, bubblecap: 1 };
}

export function buildPlayer({ name, gender, raceId, humanHeritageId, appearanceId }): Player {
  const race = RACES.find((r) => r.id === raceId) || RACES[0];
  const baseStats = addBonuses(BASE_STATS, race.bonuses);
  const inventory = getInitialInventory();
  return {
    name: name || "Liam",
    gender,
    raceId: race.id,
    humanHeritageId: race.id === "human" ? normalizeHumanHeritageId(humanHeritageId) : DEFAULT_HUMAN_HERITAGE_ID,
    appearanceId: appearanceId || DEFAULT_APPEARANCE_ID,
    level: 1,
    xp: 0,
    gold: 4,
    maxHp: 24 + baseStats.Vitality * 2,
    hp: 24 + baseStats.Vitality * 2,
    baseStats,
    inventory,
    equipment: { weapon: null, helm: null, cloak: null, trinket1: null, trinket2: null, armor: null },
    battlePouch: getDefaultBattlePouch(inventory),
    checkpointLabel: "Home",
  };
}

export function buildDefaultCompanion(): Companion {
  return {
    recruited: false,
    id: null,
    name: "No Companion Yet",
    hp: 14,
    maxHp: 14,
    level: 1,
    xp: 0,
    command: "Attack Freely",
    buffed: false,
    style: null,
    icon: null,
    role: null,
    futurePath: null,
    futurePathOptions: null,
  };
}

export function buildDefaultFlags(): GameFlags {
  return {
    metElder: false,
    elderGavePurse: false,
    smithStarterDiscountUsed: false,
    gotSmithGift: false,
    homeStashClaimed: false,
    openedChest: false,
    craftedPotion: false,
    gotPibbleTip: false,
    beatGateBattle: false,
    metNix: false,
    foundRuinNote: false,
    clearedWildBattle: false,
    reachedBramblecross: false,
    enteredBramblecross: false,
    metMayor: false,
    readBoard: false,
    boardQuestAccepted: false,
    boardQuestCompleted: false,
    marketDiscount: false,
    ennaBriefed: false,
    watchEvidenceRead: false,
    watchLedgerRead: false,
    watchMapRead: false,
    watchOrdersRead: false,
    askedHollisAboutEdden: false,
    gotDungeonLead: false,
    enteredRootCellar: false,
    openedCellarCache: false,
    readCellarSigil: false,
    readCellarMural: false,
    harvestedCellarFungus: false,
    beatCellarSkulk: false,
    beatCellarBoss: false,
    chapterOneClear: false,
    cellarEndChoice: null,
    chapterReported: false,
    studiedBriarCrown: false,
    rowanStatus: null,
    tildaStatus: null,
    mossStatus: null,
    companionChosen: false,
    companionChoice: null,
    helpedTraveler: false,
    searchedCart: false,
    cartRecoveredForAda: false,
    openedWildChest: false,
    wellVisited: false,
    pondVisited: false,
    pondForaged: false,
    usedShrine: false,
    sawShrine: false,
    foundShrineSecret: false,
    sawRoadCamp: false,
    chapterTwoStarted: false,
    chapterTwoBriefed: false,
    maraJoined: false,
    eddenVisited: false,
    eddenDrawingReceived: false,
    eddensDrawingValidated: false,
    adaSealLessonComplete: false,
    maraJob: null,
    westrootCutStudied: false,
    brokenSealWaxFound: false,
    shelterNoticeRemoved: false,
    shelterRested: false,
    lioShelterMarkFound: false,
    falseNoticeInspected: false,
    falseNoticeLensUsed: false,
    falseNoticeLanternRead: false,
    trustedLanternBeforeHollow: false,
    followedFalseDetour: false,
    crownSignRejected: false,
    crownSignLensUsed: false,
    crownDoorTried: false,
    enteredFalseCrownPassage: false,
    crownDoorKeyFound: false,
    crownDoorUnlocked: false,
    crownDoorDungeonEntered: false,
    crownDoorWaxTableCleared: false,
    crownDoorSlatsBroken: false,
    crownDoorWitnessLedgerFound: false,
    crownDoorCollarsBroken: false,
    crownDoorFalseMapRead: false,
    crownDoorDungeonCleared: false,
    cleanedLanternMarkFound: false,
    beatCrownDenGuard: false,
    crownDoorGuardDefeated: false,
    crownDenAlertLevel: 0,
    crownDenPatrolDefeated: false,
    crownDenPatrolEscaped: false,
    crownDenHoundFreed: false,
    crownDenHoundDefeated: false,
    maraQuestionedCrownDoor: false,
    willowForgeryConfirmedAtHollow: false,
    lanternSignCleaned: false,
    lanternSignCompared: false,
    understandsTrueSigns: false,
    lanternDoorTried: false,
    maraQuestionedLanternDoor: false,
    eddensDrawingRotated: false,
    maraWatchedLantern: false,
    maraConsultedAtThreshold: false,
    companionReadThreshold: false,
    noHandleStoneInspected: false,
    lioHookMarkFound: false,
    maraAskedNoHandleMark: false,
    companionReadNoHandleDoor: false,
    noHandleDoorStudied: false,
    eddenDrawingComparedAtDoor: false,
    incompleteTruthPhraseSpoken: false,
    trustedCrownSignAtHollow: false,
    forcedNoHandleDoor: false,
    forcedNoHandleDoorTwice: false,
    westrootGateOpened: false,
    westrootGateOpeningPending: false,
    cleanWestrootSolve: false,
    messyWestrootSolve: false,
    beatRoadwatcher: false,
    roadwatcherSummoned: false,
    roadwatcherPrepared: false,
    maraProtectedAtHollow: false,
    roadwatcherEncounterAvoided: false,
    roadwatcherDefeated: false,
    roadwatcherHardCleared: false,
    roadwatcherEvidenceFound: false,
    briarCrownWatchingWestroot: false,
    lioAlivePastGate: false,
    searchedWestrootThreshold: false,
    witnessNoteSent: false,
    chapterTwoClear: false,
    chapterThreeStarted: false,
    metBramwell: false,
    metNoma: false,
    metQuill: false,
    metAuntieLume: false,
    metRootbreadChild: false,
    rootbreadPromiseKept: false,
    lioKnotFound: false,
    witnessStoneFirstAttemptMissed: false,
    westrootTrustEarned: false,
    witnessStoneSequenceSolved: false,
    willowCargoExposed: false,
    cargoRunnerCaptured: false,
    cargoRunnerEscaped: false,
    chapterThreeClear: false,
    chapterFourStarted: false,
    foldedMapDecoded: false,
    captivePorterHelped: false,
    lioMessageFound: false,
    princessNameSeen: false,
    briarholdLeadFound: false,
    chapterFourClear: false,
    chapterFiveStarted: false,
    captiveLanternsRestored: false,
    lioRescued: false,
    brackenEscaped: false,
    briarCrownFactionRevealed: false,
    livingBriarMarkSeen: false,
    chapterFiveClear: false,
  };
}

export function normalizePlayerData(player: Player | null) {
  if (!player) return player;
  const equipment = {
    weapon: null,
    helm: null,
    cloak: null,
    trinket1: null,
    trinket2: null,
    armor: null,
    ...(player.equipment || {}),
  };
  return {
    ...player,
    humanHeritageId: normalizeHumanHeritageId(player.humanHeritageId as string | null),
    inventory: player.inventory || {},
    equipment,
    battlePouch: { ...getDefaultBattlePouch(player.inventory || {}), ...(player.battlePouch || {}) },
  };
}

export function normalizeCompanionData(companion: Companion | null) {
  return { ...buildDefaultCompanion(), ...(companion || {}) };
}
